In [19]:
import networkx as nx
import pandas as pd
import numpy as np
import numpy as np; import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity


part_df = pd.read_csv ('resources/Atts_agroconcept_int.csv',index_col=False,header=0)
nonpart_df = pd.read_csv ('resources/Atts_nonpart_int.csv',index_col=False,header=0)

part_df = part_df[['CC_import','CC_import_change']].T

print('The cosine similarity for the two fields, CC_import and CC_import_change, is:','\n', cosine_similarity(part_df))



The cosine similarity for the two fields, CC_import and CC_import_change, is: 
 [[1.         0.94777627]
 [0.94777627 1.        ]]


In [20]:
nonpart_df = nonpart_df[['CC_import_nonpart','CC_import_change_nonpart']].T

print('The cosine similarity for the non participants, CC_import_nonpart and CC_import_change_nonpart, is:','\n', cosine_similarity(nonpart_df))


The cosine similarity for the non participants, CC_import_nonpart and CC_import_change_nonpart, is: 
 [[1.         0.93706054]
 [0.93706054 1.        ]]


In [24]:
part_df = pd.read_csv ('resources/Atts_agroconcept_int.csv',index_col=False,header=0)
nonpart_df = pd.read_csv ('resources/Atts_nonpart_int.csv',index_col=False,header=0)

part_df = part_df[['furt_reduc','CC_import','CC_import_change']].T

print('The cosine similarity for the participants across furt_reduc, CC_import and CC_import_change is:','\n', cosine_similarity(part_df))

The cosine similarity for the participants across furt_reduc, CC_import and CC_import_change is: 
 [[1.         0.79866787 0.87805281]
 [0.79866787 1.         0.94777627]
 [0.87805281 0.94777627 1.        ]]


In [26]:

nonpart_df = pd.read_csv ('resources/Atts_nonpart_int.csv',index_col=False,header=0)

nonpart_df = nonpart_df[['furt_reduc_nonpart','CC_import_nonpart','CC_import_change_nonpart']].T

print('The cosine similarity for nonparticipants across furt_reduc_nonpart, CC_import_nonpart and CC_import_change_nonpart is:','\n', cosine_similarity(nonpart_df))

The cosine similarity for nonparticipants across furt_reduc_nonpart, CC_import_nonpart and CC_import_change_nonpart is: 
 [[1.         0.74215304 0.73843281]
 [0.74215304 1.         0.93706054]
 [0.73843281 0.93706054 1.        ]]
